name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: silverpp.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Create Solution Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake/premake5.exe vs2022

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /v:m

    - name: Prepare Pack
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd builds\bin
        copy ..\..\3rdParty\zydis\LICENSE attribution-zydis.txt
        copy ..\..\LICENSE LICENSE.txt
    
    - uses: actions/upload-artifact@v3
      with:
        name: build-win64
        path: |
          builds/bin/silverpp.exe
          builds/bin/*.dll
          builds/bin/*.txt
